### ISSUE TITLE
kernel fails to compile with gcc 6.3

### ISSUE THREAD

**Issue by patricklauer** [RadeonOpenCompute/ROCK-Kernel-Driver#18]
```
  CC [M]  drivers/gpu/drm/amd/amdgpu/amdgpu_amdkfd_gpuvm.o
drivers/gpu/drm/amd/amdgpu/amdgpu_amdkfd_gpuvm.c:408:12: error: "amdgpu_amdkfd_validate" defined but not used [-Werror=unused-function]
 static int amdgpu_amdkfd_validate(void *param, struct amdgpu_bo *bo)
            ^~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
```
Removing this function leads to the next failure:
```
drivers/gpu/drm/amd/amdgpu/../dal/dc/i2caux/dce80/i2c_sw_engine_dce80.c:53:23: error: "ddc_hw_status_addr" defined but not used [-Werror=unused-const-variable=]
 static const uint32_t ddc_hw_status_addr[] = {
                       ^~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
```
and
```
drivers/gpu/drm/amd/amdgpu/../dal/dc/core/dc_link_ddc.c:44:21: error: "dvi_hdmi_dongle_signature_str" defined but not used [-Werror=unused-const-variable=]
 static const int8_t dvi_hdmi_dongle_signature_str[] = "6140063500G";
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
Now things get exciting:
```
drivers/gpu/drm/amd/amdgpu/../dal/modules/freesync/freesync.c: In function "set_freesync_on_streams":
drivers/gpu/drm/amd/amdgpu/../dal/modules/freesync/freesync.c:503:5: error: this "if" clause does not guard... [-Werror=misleading-indentation]
     if (v_total_nominal >=
     ^~
drivers/gpu/drm/amd/amdgpu/../dal/modules/freesync/freesync.c:513:6: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the "if"
      core_freesync->dc->stream_funcs.
      ^~~~~~~~~~~~~
```
lazily patching that gives us:
```
drivers/gpu/drm/amd/amdgpu/../powerplay/hwmgr/tonga_hwmgr.c:102:22: error: "PP_ClockStretchAmountConversion" defined but not used [-Werror=unused-const-variable=]
 static const uint8_t PP_ClockStretchAmountConversion[2][6] = {
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
drivers/gpu/drm/amd/amdgpu/../powerplay/hwmgr/tonga_hwmgr.c:97:23: error: "PP_ClockStretcherDDTTable" defined but not used [-Werror=unused-const-variable=]
 static const uint32_t PP_ClockStretcherDDTTable[2][4][4] = {
                       ^~~~~~~~~~~~~~~~~~~~~~~~~
drivers/gpu/drm/amd/amdgpu/../powerplay/hwmgr/tonga_hwmgr.c:92:23: error: "PP_ClockStretcherLookupTable" defined but not used [-Werror=unused-const-variable=]
 static const uint16_t PP_ClockStretcherLookupTable[2][4] = {
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
```
drivers/gpu/drm/amd/amdgpu/../powerplay/hwmgr/polaris10_hwmgr.c:111:22: error: "polaris10_clock_stretch_amount_conversion" defined but not used [-Werror=unused-const-variable=]
 static const uint8_t polaris10_clock_stretch_amount_conversion[2][6] =
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
drivers/gpu/drm/amd/amdgpu/../powerplay/hwmgr/polaris10_hwmgr.c:106:23: error: "polaris10_clock_stretcher_ddt_table" defined but not used [-Werror=unused-const-variable=]
 static const uint32_t polaris10_clock_stretcher_ddt_table[2][4][4] =
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
drivers/gpu/drm/amd/amdgpu/../powerplay/hwmgr/polaris10_hwmgr.c:102:23: error: "polaris10_clock_stretcher_lookup_table" defined but not used [-Werror=unused-const-variable=]
 static const uint16_t polaris10_clock_stretcher_lookup_table[2][4] =
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by jamborm** [comment]
Please refrain from adding -Werror flags anywhere.  People with
slightly different compilers will be hit by this (and it actually
makes packaging ROCk needlessly painful).

Currently, the following patches add the harmful compiler switch:

$ grep -l -e '-Werror' rock*
rock-0396-drm-amd-dal-Treat-warnings-as-errors.patch
rock-0558-drm-amd-dal-Remove-the-CZ_BRINGUP-flag.patch
rock-0693-drm-amd-dal-move-virtual-hardware-header-files-to-in.patch
rock-0889-drm-amd-dal-remove-duplicated-function-definition.patch
rock-0989-amdgpu-use-NULL-instead-of-0-for-pointer.patch
rock-1010-drm-amdgpu-initialize-amdgpu_cgs_acpi_eval_object-re.patch

**Comment by kentrussell** [comment]
This should be addressed in 1.8. Please re-open if it's still present after the 1.9 release.
