### ISSUE TITLE
1.8-192 module works fine with 4.15.0-29 but fails with 4.15.0-33

### ISSUE THREAD

**Issue by ptsant** [RadeonOpenCompute/ROCK-Kernel-Driver#53]
The rock-dkms ubuntu package works fine with kernel 4.15.0-29 but not with the latest one (-33). I believe the cause is a change in vga_swithceroo.h that generates an error in amdgpu_atpx_handler.c:

```
/var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/amdgpu_atpx_handler.c:577:19: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
  .get_client_id = amdgpu_atpx_get_client_id,
                   ^
```
I have no problem using the previous kernel version on my system but thought this might help. Thanks.

**Comment by jlgreathouse** [comment]
Hi @ptsant 

We're currently [working on this issue](https://github.com/RadeonOpenCompute/ROCm/issues/510). We've identified the problem, have a patch in place, and are currently going through testing before making a release to fix it. Thanks and sorry for the problems.

**Comment by jlgreathouse** [comment]
We have released ROCm 1.8.3 (module 1.8-199) that should fix this issue with 4.15.0-33.
